services:

  laravel-docker:
    container_name: laravel-docker
    build: .
    volumes:
      - ./laravel-app:/var/www/html
    ports:
      - 80:80
  
  mysql:
    image: mysql/mysql-server:8.0
    environment:
      MYSQL_ROOT_PASSWORD: 'Odinga1#'
      MYSQL_ROOT_HOST: '%'
      MYSQL_DATABASE: 'payslack'
      MYSQL_USER: 'payslack'
      MYSQL_PASSWORD: 'Odinga1#'
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    ports:
    - 3306:3306
  
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 8888:80
    platform: linux/amd64
    environment:
      - PMA_HOST=mysql
      - PMA_PORT=3306